import { Inter, Roboto_Slab } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar/Navbar";
import Footer from "@/Components/Footer/Footer";

// const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto_Slab({ subsets: ["latin"] })
export const metadata = {
  title: "Earth Donor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={roboto.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
